name: "Terraform"

on: workflow_dispatch

permissions: read-all

jobs:
  terraform:
    name: "Terraform"

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:

      - name: Azure CLI
        run: az --help

      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUB_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
          export ARM_CLIENT_ID="${{ secrets.AZURE_CLIENT_ID }}"
          export ARM_CLIENT_SECRET="${{ secrets.AZURE_CLIENT_SECRET }}"
          export ARM_TENANT_ID="${{ secrets.AZURE_TENANT_ID }}"
          export ARM_SUBSCRIPTION_ID="${{ secrets.AZURE_SUB_ID }}"
          cd infrastructure
          terraform init

      
      - name: Terraform Validate
        id: validate
        run: |
          cd infrastructure
          terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: |
          cd infrastructure
          terraform plan -no-color -input=false

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve -input=false